### ISSUE TITLE
Run process in image as a non root user

### ISSUE THREAD

**Issue by lindsve** [tmds/build-image#15]
It is best practice (and mandated in our runtime environment) to run the process within a docker container as a non root user.

In our dockerfiles, we have something like this:

```
RUN groupadd -g 1001 appgroup
RUN useradd -u 1001 -G appgroup appuser
USER 1001
```

Can this be added to this tool as well, preferably via a tool option to set username/groupname?

**Comment by tmds** [comment]
This can be added.

The `--base ubi` images are meant to be used in OpenShift. They already run the app as user 1001 group 0.

Does this meet the requirements of your Kubernetes environment?

**Comment by lindsve** [comment]
Nice. Yes, this seem to meet the requirements that are mandated in our environment 👍

**Comment by tmds** [comment]
This should now be possible using any base.
You can give it a try by installing:
```
$ dotnet tool install -g --add-source https://www.myget.org/F/tmds --version '0.3.3-*' dotnet-build-image
```
