### ISSUE TITLE
Source Review: Try Pattern implementation is not in line with convention or expectation

### ISSUE THREAD

**Issue by brcaswell** [tmds/build-image#18]
https://github.com/tmds/build-image/blob/0f398a6b36362f4d295931d046dbdb2f1dbab1e6/src/build-image/ContainerEngine.cs#L40

We should be returning an integral value (`bool` or `int`) and using `out` param on the method. 

Edit: I referenced link to the incorrect line.

**Comment by brcaswell** [comment]
we can also refactor the method implementation at bit there as well, 
  - quite a few of those operations (collection instance of `ProcessStartInfo`) aren't caller instance dependent (since they are manifested from `Docker` and `Prodman` `const`, respectfully) and could otherwise be static readonly initialized. 
  - based on the behavior, we don't need to break out of the loop, we can `return` -- removing the need to declare the variable `version` and `command` outside of the loop.

**Comment by tmds** [comment]
If you make a PR that improves the style and readability of the code, I'll take it.

I don't intend to change it myself unless I'm making functional changes in that area.

**Comment by tmds** [comment]
Closing, as I have no plans to re-factor this code.
